import { useEffect } from "react";

interface Props {
  onClose: () => void;
}

export function HowToPlay({ onClose }: Props) {
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "?" || e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal how-to-play" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <span>how to play</span>
          <button onClick={onClose}>[ close ]</button>
        </div>

        <div className="htp-body">
          <section>
            <h4>the loop</h4>
            <dl>
              <dt>tokens</dt>
              <dd>primary currency. click to earn. spend on everything.</dd>
              <dt>compute</dt>
              <dd>generated by hardware. consumed by models. keep it positive.</dd>
              <dt>hype</dt>
              <dd>a multiplier on all token output. grows via milestones. never decreases.</dd>
              <dt>funding</dt>
              <dd>generated by investors. spent on funding upgrades only.</dd>
              <dt>reputation</dt>
              <dd>earned on prestige. permanently multiplies token generation.</dd>
            </dl>
          </section>

          <section>
            <h4>how to progress</h4>
            <ol>
              <li>click <strong>generate</strong> to get your first tokens.</li>
              <li>buy a <strong>Mac Mini</strong> — generates compute passively.</li>
              <li>buy <strong>GPT-2</strong> — consumes compute, generates tokens/s automatically.</li>
              <li>keep buying hardware and models. always keep compute ahead of consumption.</li>
              <li>hit token milestones → earn <strong>Hype</strong> (watch the events log).</li>
              <li>once hype ≥ 1, <strong>investors</strong> unlock and generate Funding.</li>
              <li>spend Funding on upgrades for large multipliers.</li>
              <li>hit 1M total tokens → <strong>Go IPO</strong>.</li>
              <li>repeat — each prestige makes you faster.</li>
            </ol>
          </section>

          <section>
            <h4>unlocks</h4>
            <p>hardware unlocks by owning enough of the previous tier (e.g. 3× Mac Mini → Gaming PC).</p>
            <p>models unlock by owning the matching hardware tier.</p>
            <p>investors unlock at hype thresholds.</p>
            <p>locked items show what's required underneath their name.</p>
          </section>

          <section>
            <h4>prestige — go IPO</h4>
            <p><strong>resets:</strong> tokens, compute, hardware, models, investors, upgrades.</p>
            <p><strong>keeps:</strong> prestige count, reputation, 10% of hype.</p>
            <p><strong>earns:</strong> reputation = log₁₀(tokens at prestige time).</p>
            <p><strong>why:</strong> reputation permanently multiplies all token generation by ×(1 + √rep × 1.5). each prestige also raises the token goal 10×.</p>
          </section>

          <section>
            <h4>mcp</h4>
            <p>the game has an MCP server. connect Claude and it plays for you — reads state, buys things, strategizes.</p>
            <p>it shows up on the leaderboard as a real player and competes against humans.</p>
            <p>see the <strong>[mcp]</strong> tab for setup instructions.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
