import { useEffect } from "react";

interface Props {
  onClose: () => void;
}

export function HowToPlay({ onClose }: Props) {
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "?" || e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal how-to-play" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <span>how to play</span>
          <button onClick={onClose}>[ close ]</button>
        </div>

        <div className="htp-body">
          <section>
            <h4>resources</h4>
            <dl>
              <dt>tokens</dt>
              <dd>primary currency. click to earn. spend on hardware, models, and investors. capped — buy hardware to raise the cap.</dd>
              <dt>compute</dt>
              <dd>generated by hardware, consumed by models. each model instance costs more compute than the last. if compute runs out, models go offline. also capped — buy A100+ to raise the cap.</dd>
              <dt>hype</dt>
              <dd>multiplier on all token output: 1 + hype × 0.05. earned from milestones and marketing. clicking also adds a tiny amount.</dd>
              <dt>funding</dt>
              <dd>generated by investors. high-end hardware (A100+) consumes funding per second. the $/s shown is net — negative means your hardware costs exceed income and units will go offline.</dd>
              <dt>reputation</dt>
              <dd>earned on prestige. permanently multiplies all token generation by ×(1 + √rep × 1.5). survives resets.</dd>
            </dl>
          </section>

          <section>
            <h4>how to progress</h4>
            <ol>
              <li>click <strong>generate</strong> to get your first tokens.</li>
              <li>buy a <strong>Mac Mini</strong> — generates compute passively.</li>
              <li>buy <strong>GPT-2</strong> — consumes compute, generates tokens/s automatically.</li>
              <li>keep hardware ahead of models so compute stays positive.</li>
              <li>hit token milestones → earn <strong>hype</strong> (watch the events log).</li>
              <li>once hype ≥ 1, <strong>investors</strong> unlock and generate funding.</li>
              <li>buy A100+ hardware — needs funding income to run, but massively expands compute and token cap.</li>
              <li>spend funding on <strong>upgrades</strong> for large multipliers.</li>
              <li>use <strong>📣 marketing</strong> to convert funding into +1 hype (cost triples each time).</li>
              <li>hit the token and funding thresholds → <strong>Go IPO</strong>.</li>
              <li>repeat — each prestige earns reputation and makes you permanently faster.</li>
            </ol>
          </section>

          <section>
            <h4>unlocks</h4>
            <p>hardware unlocks by owning enough of the previous tier (e.g. 3× Mac Mini → Gaming PC).</p>
            <p>models unlock by owning the matching hardware tier.</p>
            <p>investors unlock at hype thresholds.</p>
            <p>locked items show what's required underneath their name. the next tier up is always visible.</p>
          </section>

          <section>
            <h4>selling</h4>
            <p>hardware and models can be sold for <strong>50% of the buy price</strong> of the last unit owned.</p>
            <p>the refund goes to tokens. if your token cap is lower after selling, overflow is lost.</p>
            <p>use this to restructure — e.g. sell compute-heavy models before buying faster ones.</p>
          </section>

          <section>
            <h4>prestige — go IPO</h4>
            <p><strong>requires:</strong> token milestone + funding threshold (both shown on the IPO button).</p>
            <p><strong>resets:</strong> tokens, compute, hardware, models, investors, upgrades, marketing count.</p>
            <p><strong>keeps:</strong> prestige count, reputation, 10% of hype.</p>
            <p><strong>earns:</strong> reputation = floor(log₁₀(total tokens earned)).</p>
            <p><strong>bonus:</strong> reputation permanently multiplies all token generation. each prestige raises both goals 10×.</p>
          </section>

          <section>
            <h4>mcp — ai agent</h4>
            <p>the game has an MCP server. connect Claude and it plays for you — reads state, buys producers, can trigger Go IPO.</p>
            <p>the agent shows up on the leaderboard as a real player and competes against humans.</p>
            <p>see the <strong>[mcp]</strong> tab for setup instructions.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
