import type { GameState } from "@ai-hype/shared";
import { prestigeTokenThreshold, reputationMultiplier } from "@ai-hype/shared";
import { fmt, fmtRate } from "../lib/format.js";

interface Props {
  state: GameState;
}

interface ResourceProps {
  label: string;
  value: string;
  rate: string;
  rateNegative?: boolean;
  tooltip: string;
  warn?: string;
}

function Resource({ label, value, rate, rateNegative, tooltip, warn }: ResourceProps) {
  return (
    <div className="resource" title={tooltip}>
      <span className="label">{label}</span>
      <span className="value">{value}</span>
      <span className={`rate ${rateNegative ? "negative" : ""}`}>{rate}</span>
      {warn && <span className="resource-warn">⚠ {warn}</span>}
    </div>
  );
}

export function ResourceBar({ state }: Props) {
  const canPrestige = state.totalTokensEarned.gte(prestigeTokenThreshold(state.prestigeCount));
  const computeDeficit = state.computePerSecond.lt(0);

  return (
    <div className="resource-bar">
      <Resource
        label="tokens"
        value={fmt(state.tokens)}
        rate={fmtRate(state.tokensPerSecond)}
        tooltip="Primary currency. Click to earn. Spent on everything."
      />
      <Resource
        label="compute"
        value={fmt(state.compute)}
        rate={(state.computePerSecond.gte(0) ? "+" : "") + fmtRate(state.computePerSecond)}
        rateNegative={computeDeficit}
        tooltip="Generated by hardware. Consumed by models. Keep it positive."
        warn={computeDeficit ? "deficit — models running slow" : undefined}
      />
      <Resource
        label="hype"
        value={state.hype.toFixed(1)}
        rate={`×${(1 + state.hype).toFixed(1)} multiplier`}
        tooltip="Global multiplier on all token generation. Earned from milestones. Never decreases."
      />
      <Resource
        label="funding"
        value={`$${fmt(state.funding)}`}
        rate={fmtRate(state.fundingPerSecond)}
        tooltip="Generated by investors. Spent on funding upgrades only."
      />
      {state.prestigeCount > 0 && (
        <Resource
          label="reputation"
          value={String(state.reputation)}
          rate={`×${reputationMultiplier(state.reputation).toFixed(1)} bonus`}
          tooltip="Earned on prestige. Permanently multiplies all token generation. Survives resets."
        />
      )}
      {canPrestige && (
        <div className="prestige-hint">★ ready to launch a startup</div>
      )}
    </div>
  );
}
