import type { GameState } from "@ai-hype/shared";
import { prestigeTokenThreshold, reputationMultiplier } from "@ai-hype/shared";
import { fmt, fmtRate } from "../lib/format.js";

interface Props {
  state: GameState;
}

interface ResourceProps {
  label: string;
  value: string;
  rate: string;
  rateNegative?: boolean;
  tooltip: string;
  full?: boolean;
}

function Resource({ label, value, rate, rateNegative, tooltip, full }: ResourceProps) {
  return (
    <div className="resource" title={tooltip}>
      <span className="label">{label}</span>
      <span className="value">
        {value}
        {full && <span className="cap-full"> FULL</span>}
      </span>
      <span className={`rate ${rateNegative ? "negative" : ""}`}>{rate}</span>
    </div>
  );
}

export function ResourceBar({ state }: Props) {
  const canPrestige = state.totalTokensEarned.gte(prestigeTokenThreshold(state.prestigeCount));
  const tokenCap = state.tokenCap;
  const computeCap = state.computeCap;

  return (
    <div className="resource-bar">
      <Resource
        label="tokens"
        value={`${fmt(state.tokens)} / ${fmt(tokenCap)}`}
        rate={fmtRate(state.tokensPerSecond)}
        tooltip="Token cap: buy Mac Mini (+500), Gaming PC (+8k), A100 (+30k), or models to increase"
        full={state.tokens.gte(tokenCap)}
      />
      <Resource
        label="compute"
        value={`${fmt(state.compute)} / ${fmt(computeCap)}`}
        rate={(state.computePerSecond.gte(0) ? "+" : "") + fmtRate(state.computePerSecond)}
        rateNegative={state.computePerSecond.lt(0)}
        tooltip="Compute cap: buy A100 (+500), TPU Pod (+2k), GPU Cluster (+10k) to increase"
        full={state.compute.gte(computeCap)}
      />
      <Resource
        label="hype"
        value={state.hype.toFixed(1)}
        rate={`×${(1 + state.hype * 0.05).toFixed(2)} multiplier`}
        tooltip="Multiplies token generation by (1 + hype × 0.05). Earned from milestones."
      />
      <Resource
        label="funding"
        value={`$${fmt(state.funding)}`}
        rate={(state.fundingPerSecond.gte(0) ? "+" : "") + fmtRate(state.fundingPerSecond)}
        rateNegative={state.fundingPerSecond.lt(0)}
        tooltip="Generated by investors. Sustains high-end hardware (A100+). Negative = hardware costs exceed income."
      />
      {state.prestigeCount > 0 && (
        <Resource
          label="reputation"
          value={String(state.reputation)}
          rate={`×${reputationMultiplier(state.reputation).toFixed(1)} bonus`}
          tooltip="Earned on prestige. Permanently multiplies all token generation. Survives resets."
        />
      )}
      {canPrestige && (
        <div className="prestige-hint">★ ready to go IPO</div>
      )}
    </div>
  );
}
